export const schedule3 = {
  error_code: -1,
  message: "",
  data: {
    term: "17182",
    data: [
      {
        classid: "5596",
        courseid: "2100075",
        coursename: "概率论与数理统计1",
        coursetype: "数学",
        coursenature: "必修",
        credit: "3.0",
        teacher: "杨玲玲",
        arrange: [
          {
            week: "单双周",
            day: "7",
            start: "1",
            end: "3",
            room: "45楼B118",
          },
        ],
        week: {
          start: "4",
          end: "14",
        },
        college: "数学学院",
        campus: "北洋园校区",
        ext: "重修",
      },
      {
        classid: "5531",
        courseid: "2111140",
        coursename: "马克思主义基本原理",
        coursetype: "思想政治理论",
        coursenature: "必修",
        credit: "3.0",
        teacher: "孙利",
        arrange: [
          {
            week: "单双周",
            day: "7",
            start: "7",
            end: "8",
            room: "46楼A110",
          },
        ],
        week: {
          start: "4",
          end: "14",
        },
        college: "马克思主义学院",
        campus: "北洋园校区",
        ext: "重修",
      },
      {
        classid: "3839",
        courseid: "2111295",
        coursename: "大学英语4",
        coursetype: "外语",
        coursenature: "必修",
        credit: "2.0",
        teacher: "李小红",
        arrange: [
          {
            week: "单双周",
            day: "1",
            start: "7",
            end: "8",
            room: "48楼210",
          },
        ],
        week: {
          start: "1",
          end: "16",
        },
        college: "文学院",
        campus: "北洋园校区",
        ext: "",
      },
      {
        classid: "3667",
        courseid: "2180273",
        coursename: "虚拟现实概论",
        coursetype: "专业选修",
        coursenature: "选修",
        credit: "2.0",
        teacher: "翁仲铭",
        arrange: [
          {
            week: "单双周",
            day: "3",
            start: "7",
            end: "8",
            room: "45楼B203",
          },
          {
            week: "单双周",
            day: "5",
            start: "3",
            end: "4",
            room: "45楼B203",
          },
        ],
        week: {
          start: "11",
          end: "16",
        },
        college: "软件学院",
        campus: "北洋园校区",
        ext: "",
      },
      {
        classid: "3665",
        courseid: "2180163",
        coursename: "数据库原理（双语）",
        coursetype: "学科基础",
        coursenature: "必修",
        credit: "3.5",
        teacher: "王征",
        arrange: [
          {
            week: "单双周",
            day: "1",
            start: "3",
            end: "4",
            room: "45楼B304",
          },
          {
            week: "单双周",
            day: "3",
            start: "1",
            end: "2",
            room: "45楼B307",
          },
        ],
        week: {
          start: "9",
          end: "16",
        },
        college: "软件学院",
        campus: "北洋园校区",
        ext: "",
      },
      {
        classid: "3664",
        courseid: "2180205",
        coursename: "计算机组成原理",
        coursetype: "学科基础",
        coursenature: "必修",
        credit: "4.0",
        teacher: "章亦葵",
        arrange: [
          {
            week: "单双周",
            day: "2",
            start: "1",
            end: "2",
            room: "45楼B304",
          },
          {
            week: "单双周",
            day: "4",
            start: "3",
            end: "4",
            room: "45楼B304",
          },
        ],
        week: {
          start: "11",
          end: "16",
        },
        college: "软件学院",
        campus: "北洋园校区",
        ext: "",
      },
      {
        classid: "3663",
        courseid: "2180120",
        coursename: "计算机网络（双语）",
        coursetype: "学科基础",
        coursenature: "必修",
        credit: "3.5",
        teacher: "毕重科",
        arrange: [
          {
            week: "单双周",
            day: "1",
            start: "5",
            end: "6",
            room: "45楼B310",
          },
          {
            week: "单双周",
            day: "3",
            start: "3",
            end: "4",
            room: "45楼B118",
          },
        ],
        week: {
          start: "1",
          end: "16",
        },
        college: "软件学院",
        campus: "北洋园校区",
        ext: "",
      },
      {
        classid: "3253",
        courseid: "2180273",
        coursename: "虚拟现实概论",
        coursetype: "专业选修",
        coursenature: "选修",
        credit: "2.0",
        teacher: "陶文源",
        arrange: [
          {
            week: "单双周",
            day: "3",
            start: "7",
            end: "8",
            room: "45楼B203",
          },
          {
            week: "单双周",
            day: "5",
            start: "3",
            end: "4",
            room: "45楼B203",
          },
        ],
        week: {
          start: "9",
          end: "10",
        },
        college: "软件学院",
        campus: "北洋园校区",
        ext: "",
      },
      {
        classid: "3036",
        courseid: "2310004",
        coursename: "羽毛球",
        coursetype: "体育",
        coursenature: "必修",
        credit: "1.0",
        teacher: "戴卫平",
        arrange: [
          {
            week: "单双周",
            day: "4",
            start: "5",
            end: "6",
            room: "",
          },
        ],
        week: {
          start: "1",
          end: "16",
        },
        college: "体育部",
        campus: "北洋园校区",
        ext: "",
      },
      {
        classid: "2270",
        courseid: "2180256",
        coursename: "专业外语（英）",
        coursetype: "学科基础",
        coursenature: "必修",
        credit: "2.0",
        teacher: "Austin K.",
        arrange: [
          {
            week: "单双周",
            day: "2",
            start: "5",
            end: "6",
            room: "33楼114",
          },
          {
            week: "单双周",
            day: "4",
            start: "7",
            end: "8",
            room: "33楼114",
          },
        ],
        week: {
          start: "1",
          end: "8",
        },
        college: "软件学院",
        campus: "北洋园校区",
        ext: "",
      },
      {
        classid: "2269",
        courseid: "2180255",
        coursename: "算法设计与分析（双语）",
        coursetype: "学科基础",
        coursenature: "必修",
        credit: "2.0",
        teacher: "王征",
        arrange: [
          {
            week: "单双周",
            day: "2",
            start: "7",
            end: "8",
            room: "33楼104",
          },
          {
            week: "单双周",
            day: "3",
            start: "7",
            end: "8",
            room: "33楼109",
          },
        ],
        week: {
          start: "1",
          end: "8",
        },
        college: "软件学院",
        campus: "北洋园校区",
        ext: "",
      },
      {
        classid: "2268",
        courseid: "2180241",
        coursename: "程序设计实践3",
        coursetype: "课程设计",
        coursenature: "必修",
        credit: "1.0",
        teacher: "Eliza",
        arrange: [
          {
            week: "单双周",
            day: "5",
            start: "1",
            end: "4",
            room: "",
          },
        ],
        week: {
          start: "3",
          end: "8",
        },
        college: "软件学院",
        campus: "北洋园校区",
        ext: "",
      },
      {
        classid: "2267",
        courseid: "2180205",
        coursename: "计算机组成原理",
        coursetype: "学科基础",
        coursenature: "必修",
        credit: "4.0",
        teacher: "李幼萌",
        arrange: [
          {
            week: "单双周",
            day: "2",
            start: "1",
            end: "2",
            room: "45楼B304",
          },
          {
            week: "单双周",
            day: "4",
            start: "3",
            end: "4",
            room: "45楼B304",
          },
        ],
        week: {
          start: "1",
          end: "10",
        },
        college: "软件学院",
        campus: "北洋园校区",
        ext: "",
      },
      {
        classid: "2266",
        courseid: "2180169",
        coursename: "C#程序设计语言与.Net框架基础（双语）",
        coursetype: "专业选修",
        coursenature: "选修",
        credit: "2.5",
        teacher: "章亦葵",
        arrange: [
          {
            week: "单双周",
            day: "1",
            start: "9",
            end: "10",
            room: "45楼B304",
          },
          {
            week: "单周",
            day: "3",
            start: "9",
            end: "10",
            room: "45楼B304",
          },
        ],
        week: {
          start: "1",
          end: "16",
        },
        college: "软件学院",
        campus: "北洋园校区",
        ext: "",
      },
      {
        classid: "2265",
        courseid: "2180163",
        coursename: "数据库原理（双语）",
        coursetype: "学科基础",
        coursenature: "必修",
        credit: "3.5",
        teacher: "李森",
        arrange: [
          {
            week: "单双周",
            day: "1",
            start: "3",
            end: "4",
            room: "45楼B304",
          },
          {
            week: "单双周",
            day: "3",
            start: "1",
            end: "2",
            room: "45楼B307",
          },
        ],
        week: {
          start: "1",
          end: "8",
        },
        college: "软件学院",
        campus: "北洋园校区",
        ext: "",
      },
      {
        classid: "2264",
        courseid: "2180128",
        coursename: "汇编语言程序设计",
        coursetype: "学科基础",
        coursenature: "必修",
        credit: "2.0",
        teacher: "王征",
        arrange: [
          {
            week: "单双周",
            day: "2",
            start: "3",
            end: "4",
            room: "45楼B118",
          },
          {
            week: "单双周",
            day: "4",
            start: "1",
            end: "2",
            room: "45楼B118",
          },
        ],
        week: {
          start: "9",
          end: "16",
        },
        college: "软件学院",
        campus: "北洋园校区",
        ext: "",
      },
      {
        classid: "2262",
        courseid: "2180119",
        coursename: "计算机新技术与产业发展",
        coursetype: "研究与创新",
        coursenature: "选修",
        credit: "1.0",
        teacher: "魏建国",
        arrange: [
          {
            week: "单双周",
            day: "3",
            start: "5",
            end: "6",
            room: "46楼A309",
          },
        ],
        week: {
          start: "1",
          end: "8",
        },
        college: "软件学院",
        campus: "北洋园校区",
        ext: "",
      },
      {
        classid: "2261",
        courseid: "2180101",
        coursename: "移动平台应用开发",
        coursetype: "专业选修",
        coursenature: "选修",
        credit: "1.5",
        teacher: "潘刚",
        arrange: [
          {
            week: "单双周",
            day: "2",
            start: "9",
            end: "10",
            room: "46楼A306",
          },
          {
            week: "单双周",
            day: "4",
            start: "9",
            end: "10",
            room: "46楼A306",
          },
        ],
        week: {
          start: "9",
          end: "16",
        },
        college: "软件学院",
        campus: "北洋园校区",
        ext: "",
      },
      {
        classid: "2259",
        courseid: "2100347",
        coursename: "物理实验B",
        coursetype: "物理",
        coursenature: "必修",
        credit: "1.0",
        teacher: "杨洋",
        arrange: [
          {
            week: "双周",
            day: "3",
            start: "9",
            end: "12",
            room: "",
          },
        ],
        week: {
          start: "1",
          end: "16",
        },
        college: "理学院",
        campus: "北洋园校区",
        ext: "",
      },
    ],
    week: 3,
    term_start: 1520179200,
    updated_at: "2018-03-29 12:24:22",
  },
}

export const schedule2 = {
  error_code: -1,
  message: "",
  data: {
    term: "19201",
    data: [
      {
        classid: "00205",
        courseid: "2010158",
        coursename: "\u5de5\u7a0b\u529b\u5b66",
        coursetype: "",
        coursenature: "",
        credit: "3.0",
        teacher: "\u5218\u957f\u6839(\u526f\u6559\u6388)",
        arrange: [],
        week: { start: "4", end: "19" },
        college: "",
        campus: "",
        ext: "",
      },
      {
        classid: "05308",
        courseid: "2070665",
        coursename:
          "\u7b80\u5355\u9020\u5c31\u795e\u5947--\u5bcc\u52d2\u70ef\u3001\u78b3\u7eb3\u7c73\u7ba1\u548c\u77f3\u58a8\u70ef",
        coursetype: "",
        coursenature: "",
        credit: "1.0",
        teacher: "\u6768\u5168\u7ea2(\u6559\u6388)",
        arrange: [],
        week: { start: "5", end: "8" },
        college: "",
        campus: "",
        ext: "",
      },
      {
        classid: "03325",
        courseid: "2080369",
        coursename: "\u6750\u6599\u5de5\u7a0b\u5bfc\u8bba",
        coursetype: "",
        coursenature: "",
        credit: "1.0",
        teacher: "\u4f55\u6625\u5e74(\u6559\u6388)",
        arrange: [],
        week: { start: "4", end: "11" },
        college: "",
        campus: "",
        ext: "",
      },
      {
        classid: "03148",
        courseid: "2080466",
        coursename: "\u6750\u6599\u53d1\u5c55\u4e0e\u5bb6\u56fd\u60c5\u6000",
        coursetype: "",
        coursenature: "",
        credit: "1.0",
        teacher: "\u6731\u80dc\u5229(\u6559\u6388)",
        arrange: [],
        week: { start: "12", end: "19" },
        college: "",
        campus: "",
        ext: "",
      },
      {
        classid: "03147",
        courseid: "2080467",
        coursename: "\u4e2d\u56fd\u4f20\u7edf\u6587\u5316\u6982\u8ff0",
        coursetype: "",
        coursenature: "",
        credit: "1.0",
        teacher: "\u5218\u79c0\u56fd(\u526f\u7814\u7a76\u5458)",
        arrange: [],
        week: { start: "4", end: "11" },
        college: "",
        campus: "",
        ext: "",
      },
      {
        classid: "01534",
        courseid: "2090024",
        coursename: "\u7ba1\u7406\u6982\u8bba",
        coursetype: "",
        coursenature: "",
        credit: "2.0",
        teacher: "\u5434\u6d25(\u8bb2\u5e08)",
        arrange: [],
        week: { start: "4", end: "19" },
        college: "",
        campus: "",
        ext: "",
      },
      {
        classid: "05368",
        courseid: "2090700",
        coursename: "\u98ce\u9669\u7ba1\u7406\u4e0e\u4fdd\u9669",
        coursetype: "",
        coursenature: "",
        credit: "3.0",
        teacher: "\u95eb\u4e1c\u73b2(\u526f\u6559\u6388)",
        arrange: [],
        week: { start: "4", end: "18" },
        college: "",
        campus: "",
        ext: "",
      },
      {
        classid: "03327",
        courseid: "2100075",
        coursename: "\u6982\u7387\u8bba\u4e0e\u6570\u7406\u7edf\u8ba11",
        coursetype: "",
        coursenature: "",
        credit: "3.0",
        teacher: "\u6768\u73b2\u73b2(\u8bb2\u5e08)",
        arrange: [],
        week: { start: "4", end: "19" },
        college: "",
        campus: "",
        ext: "",
      },
      {
        classid: "00204",
        courseid: "2100098",
        coursename: "\u5927\u5b66\u7269\u74062B",
        coursetype: "",
        coursenature: "",
        credit: "3.0",
        teacher: "\u8096\u7acb\u5cf0(\u8bb2\u5e08)",
        arrange: [],
        week: { start: "4", end: "19" },
        college: "",
        campus: "",
        ext: "",
      },
      {
        classid: "00655",
        courseid: "2100268",
        coursename: "\u6709\u673a\u5316\u5b66A",
        coursetype: "",
        coursenature: "",
        credit: "2.0",
        teacher: "\u5510\u5411\u9633(\u6559\u6388)",
        arrange: [],
        week: { start: "4", end: "19" },
        college: "",
        campus: "",
        ext: "",
      },
      {
        classid: "01866",
        courseid: "2100346",
        coursename: "\u7269\u7406\u5b9e\u9a8cA",
        coursetype: "",
        coursenature: "",
        credit: "1.0",
        teacher: "\u5b9e\u9a8c\u6559\u5e088",
        arrange: [],
        week: { start: "4", end: "19" },
        college: "",
        campus: "",
        ext: "",
      },
      {
        classid: "01532",
        courseid: "2111140",
        coursename: "\u9a6c\u514b\u601d\u4e3b\u4e49\u57fa\u672c\u539f\u7406",
        coursetype: "",
        coursenature: "",
        credit: "3.0",
        teacher: "\u674e\u5149\u798f(\u6559\u6388)",
        arrange: [],
        week: { start: "4", end: "19" },
        college: "",
        campus: "",
        ext: "",
      },
      {
        classid: "04966",
        courseid: "2111294",
        coursename: "\u5927\u5b66\u82f1\u8bed3",
        coursetype: "",
        coursenature: "",
        credit: "2.0",
        teacher: "\u6c5f\u6ee8(\u526f\u6559\u6388)",
        arrange: [],
        week: { start: "4", end: "19" },
        college: "",
        campus: "",
        ext: "",
      },
      {
        classid: "02407",
        courseid: "2160213",
        coursename: "\u8ba1\u7b97\u673a\u8f6f\u4ef6\u6280\u672f\u57fa\u78402",
        coursetype: "",
        coursenature: "",
        credit: "3.0",
        teacher: "\u4e8e\u6c38\u65b0(\u526f\u6559\u6388)",
        arrange: [],
        week: { start: "4", end: "19" },
        college: "",
        campus: "",
        ext: "",
      },
      {
        classid: "05838",
        courseid: "2310003",
        coursename: "\u4f53\u80b2C (\u6392\u7403)",
        coursetype: "",
        coursenature: "",
        credit: "1.0",
        teacher: "\u5218\u5e7f\u9e3f(\u526f\u6559\u6388)",
        arrange: [],
        week: { start: "4", end: "19" },
        college: "",
        campus: "",
        ext: "",
      },
      {
        classid: "05409",
        courseid: "4010001",
        coursename: "\u76f8\u58f0\u827a\u672f\u8d4f\u6790",
        coursetype: "",
        coursenature: "",
        credit: "2.0",
        teacher: "\u5f20\u5efa\u658c(\u52a9\u6559\uff08\u653f\uff09)",
        arrange: [],
        week: { start: "4", end: "18" },
        college: "",
        campus: "",
        ext: "",
      },
      {
        classid: "01865",
        courseid: "5100058",
        coursename: "\u96c6\u4e2d\u519b\u4e8b\u8bad\u7ec31",
        coursetype: "",
        coursenature: "",
        credit: "3.0",
        teacher: "\u6881\u5149\u5f3a(\u526f\u6559\u6388\uff08\u653f\uff09)",
        arrange: [],
        week: { start: "1", end: "3" },
        college: "",
        campus: "",
        ext: "",
      },
    ],
  },
}

export const schedule1 = {
  error_code: -1,
  message: "",
  data: {
    term: "17182",
    data: [
      {
        classid: "5596",
        courseid: "2100075",
        coursename: "概率论与数理统计1",
        coursetype: "数学",
        coursenature: "必修",
        credit: "3.0",
        teacher: "杨玲玲",
        arrange: [
          {
            week: "单双周",
            day: "4",
            start: "2",
            end: "4",
            room: "45楼B118",
          },
        ],
        week: {
          start: "4",
          end: "14",
        },
        college: "数学学院",
        campus: "北洋园校区",
        ext: "重修",
      },
      {
        classid: "5531",
        courseid: "2111140",
        coursename: "马克思主义基本原理",
        coursetype: "思想政治理论",
        coursenature: "必修",
        credit: "2.5",
        teacher: "孙利",
        arrange: [
          {
            week: "单双周",
            day: "1",
            start: "3",
            end: "4",
            room: "46楼A110",
          },
          {
            week: "单双周",
            day: "2",
            start: "1",
            end: "4",
            room: "46楼A110",
          },
          {
            week: "单双周",
            day: "3",
            start: "4",
            end: "5",
            room: "45楼B118",
          },
          {
            week: "单双周",
            day: "4",
            start: "2",
            end: "4",
            room: "45楼B118",
          },
        ],
        week: {
          start: "4",
          end: "14",
        },
        college: "马克思主义学院",
        campus: "北洋园校区",
        ext: "重修",
      },
      {
        classid: "3839",
        courseid: "2111295",
        coursename: "大学英语4",
        coursetype: "外语",
        coursenature: "必修",
        credit: "2.0",
        teacher: "李小红",
        arrange: [
          {
            week: "单双周",
            day: "1",
            start: "3",
            end: "4",
            room: "48楼210",
          },
          {
            week: "单双周",
            day: "2",
            start: "3",
            end: "5",
            room: "48楼210",
          },
          {
            week: "单双周",
            day: "3",
            start: "1",
            end: "6",
            room: "45楼B118",
          },
          {
            week: "单双周",
            day: "4",
            start: "2",
            end: "4",
            room: "45楼B118",
          },
        ],
        week: {
          start: "1",
          end: "16",
        },
        college: "文学院",
        campus: "北洋园校区",
        ext: "",
      }
    ],
    week: 3,
    term_start: 1520179200,
    updated_at: "2018-03-29 12:24:22",
  },
}
